; =============================================================================
;
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
;
;
; Get board information with $>  pio boards
;
;==============================================================================
;
[platformio]
default_envs = esp32dev
;
[common]
build_flags       = -Wno-unused-function -DLV_CONF_SKIP=1 -std=c++17
build_src_flags   = --include=/home/frankm/Arduino/sketches/sources/util/platformio.h
                    -I/home/frankm/Arduino/sketches/sources
                    -I/home/frankm/Arduino/libraries/TFT_eSPI
                    -Wall -Wextra -std=c++17
                    -DDEVICE_DISPLAY_FILE=\"src/web/SensorBox_LCD_test.cpp\"
lib_deps_lvgl     = lvgl
lib_deps_fs       = littlefs
lib_deps_default  = Wire
;
;==============================================================================
[env]
framework         = arduino
monitor_speed     = 115200
upload_speed      = 230400
upload_protocol   = esptool
lib_compat_mode   = strict
build_flags       = ${common.build_flags}
build_src_flags   = ${common.build_src_flags}
lib_deps          = ${common.lib_deps_lvgl}, ${common.lib_deps_default}, ${common.lib_deps_fs}
;
;
;==============================================================================
; esp32dev                             ESP32    240MHz       4MB      320KB   Espressif ESP32 Dev Module
[env:esp32dev]
platform          = espressif32
board             = esp32dev
build_src_flags   = ${common.build_src_flags} -DARDUINO_VARIANT=\"esp32dev\"
;
; =============================================================================
; lolin_s2_mini                        ESP32S2  240MHz       4MB      320KB   WEMOS LOLIN S2 Mini
[env:lolin_s2_mini]
platform          = espressif32
board             = lolin_s2_mini
upload_speed      = 921600
board_build.mcu   = esp32s2
build_src_flags   = ${common.build_src_flags} -DESP32=1 -DARDUINO_VARIANT=\"lolin_s2_mini\"
;
; =============================================================================
; These are the ESP32 C3 super mini from aliexpress
; lolin_c3_mini                        ESP32C3  160MHz       4MB      320KB   WEMOS LOLIN C3 Mini
[env:lolin_c3_mini]
platform          = espressif32
board             = lolin_c3_mini
upload_speed      = 921600
board_build.mcu   = esp32c3
board_build.partitions = partitions/OTA-1.7MB-SPIFFS-500kB.csv
build_src_flags   = ${common.build_src_flags} -DESP32=1 -DARDUINO_VARIANT=\"lolin_c3_mini\"
;
; =============================================================================
; Default for ESP8266 Wemos mini 
; =============================================================================
[env:wemos-d1]
platform          = espressif8266
board             = d1
build_src_flags   = ${env.build_src_flags} -DESP8266=1 -DARDUINO_VARIANT=\"ESP8266\"
; change microcontroller
board_build.mcu   = esp8266
; change MCU frequency
board_build.f_cpu = 80000000L
;
; =============================================================================
[env:stm32]
platform          = ststm32
board             = genericSTM32F412CE
build_flags       = ${env.build_flags} -DSTM32=1 -DARDUINO_VARIANT=\"STM32\"
lib_deps          = ${common.lib_deps_default}, ${common.lib_deps_fs} FS
upload_protocol   = blackmagic
; change MCU frequency
board_build.f_cpu = 100000000L
;
;==============================================================================
[env:uno]
platform          = atmelavr
board             = uno
build_flags       = ${common.build_flags} -DARDUINO=1 -DARDUINO_VARIANT=\"ARDUINO\"
; change microcontroller
board_build.mcu   = atmega328p
board_build.f_cpu = 80000000L
monitor_speed     = 115200
; =============================================================================
